// @vitest-environment jsdom
import { setFieldValue } from '@/test/fields'
import { afterEach, describe, expect, it } from 'vitest'
import { cleanup, fireEvent, render, screen, within } from '@testing-library/react'
import App from '@/App'

afterEach(cleanup)
const click = (name: string) => fireEvent.click(screen.getByRole('button', { name }))
const change = (label: string, value: string) => setFieldValue(screen.getByLabelText(label), value)
const rows = () => Array.from(document.querySelectorAll<HTMLElement>('.audit-compact-row'))
const panel = () => screen.getByRole('complementary')
const openAudit = () => { render(<App />); click('Audit') }

async function projectMenu(item: string) {
  fireEvent.keyDown(screen.getByRole('button', { name: /^Project:/ }), { key: 'Enter' })
  fireEvent.click(await screen.findByRole('menuitemradio', { name: item }))
}
async function rowMenu(id: string, action: string) {
  fireEvent.keyDown(screen.getByRole('button', { name: `Дії із зауваженням ${id}` }), { key: 'Enter' })
  fireEvent.click(await screen.findByRole('menuitem', { name: action }))
}

describe('Audit table-first UX', () => {
  it('keeps rows compact and uses the right panel as the only detail view', () => {
    openAudit()
    expect(rows()).toHaveLength(4)
    expect(screen.queryByText('Що виявлено')).toBeNull()
    fireEvent.click(rows()[0])
    expect(screen.getByRole('complementary')).toBeTruthy()
    expect(screen.getByText('Що виявлено')).toBeTruthy()
    expect(screen.getByText('Expected / Очікуваний результат')).toBeTruthy()
    expect(screen.getByText('Actual / Фактичний результат')).toBeTruthy()
    expect(screen.getByRole('region', { name: 'Evidence / Докази' })).toBeTruthy()
    click('Закрити панель Audit')
    expect(screen.queryByRole('complementary')).toBeNull()
    expect(document.querySelector('.audit-with-panel')).toBeNull()
  })

  it('combines header filters and clears them only when active', async () => {
    openAudit()
    expect(screen.queryByRole('button', { name: 'Очистити фільтри' })).toBeNull()
    fireEvent.keyDown(screen.getByRole('button', { name: 'Area' }), { key: 'Enter' })
    fireEvent.click(await screen.findByRole('menuitemcheckbox', { name: 'Landing' }))
    expect(rows()).toHaveLength(1)
    fireEvent.keyDown(screen.getByRole('button', { name: 'Status' }), { key: 'Enter' })
    fireEvent.click(await screen.findByRole('menuitemcheckbox', { name: 'Open' }))
    expect(rows()).toHaveLength(1)
    fireEvent.keyDown(screen.getByRole('button', { name: 'Severity' }), { key: 'Enter' })
    fireEvent.click(await screen.findByRole('menuitemcheckbox', { name: 'High' }))
    expect(rows()).toHaveLength(1)
    expect(screen.getByRole('button', { name: 'Очистити фільтри' })).toBeTruthy()
    click('Очистити фільтри')
    expect(rows()).toHaveLength(4)
    expect(screen.queryByRole('button', { name: 'Очистити фільтри' })).toBeNull()
  })

  it('sorts dates newest and oldest from the Date header and filters a date range', async () => {
    openAudit()
    const dateHeader = screen.getByRole('button', { name: 'Date' })
    fireEvent.click(dateHeader)
    fireEvent.click(await screen.findByRole('radio', { name: 'Спочатку старі' }))
    expect(rows()[0].textContent).toContain('10.09.2026')
    fireEvent.click(screen.getByRole('radio', { name: 'Спочатку нові' }))
    expect(rows()[0].textContent).toContain('13.09.2026')
    change('Від', '2026-09-11')
    change('До', '2026-09-12')
    expect(rows()).toHaveLength(2)
  })

  it('opens the same right panel for creating an item, then edits and deletes it', async () => {
    openAudit()
    click('Додати зауваження')
    expect(panel()).toBeTruthy()
    expect(within(panel()).getByText('Новий запис')).toBeTruthy()
    change('Назва', 'Новое зауваження')
    change('Що виявлено', 'Описание проблемы')
    change('Location / де виявлено', 'Новый экран')
    change('Expected / Очікуваний результат', 'Ожидается корректное поведение')
    change('Actual / Фактичний результат', 'Фактическое поведение отличается')
    change('Note', 'Скриншот не приложен')
    fireEvent.click(within(panel()).getByRole('combobox', { name: 'Area' }))
    change('Додати Area', 'Checkout')
    click('Додати Area')
    fireEvent.keyDown(screen.getByLabelText('Додати Area'), { key: 'Escape' })
    fireEvent.click(within(panel()).getByRole('combobox', { name: 'Type' }))
    click('Bug')
    click('Створити зауваження')
    expect(rows()).toHaveLength(5)
    expect(rows().some(row => row.textContent?.includes('Новое зауваження'))).toBe(true)
    await rowMenu('AUD-005', 'Змінити')
    change('Назва', 'Изменённое зауваження')
    click('Зберегти зміни')
    expect(rows().some(row => row.textContent?.includes('Изменённое зауваження'))).toBe(true)
    await rowMenu('AUD-005', 'Видалити')
    click('Видалити зауваження')
    expect(rows()).toHaveLength(4)
  })

  it('keeps Audit project-specific and QP Notes empty', async () => {
    openAudit()
    await projectMenu('QP Notes')
    expect(rows()).toHaveLength(0)
    expect(screen.getByText('Зауважень поки немає. Додайте перше зауваження.')).toBeTruthy()
    await projectMenu('Voicli')
    expect(rows()).toHaveLength(4)
  })
})

describe('Audit dictionaries and combined search', () => {
  it('combines search across ID and title with every category and date, retaining headers for no matches', async () => {
    openAudit()
    change('Пошук за ID або назвою', 'aud-001')
    expect(rows()).toHaveLength(1)
    change('Пошук за ID або назвою', 'НЕПОМІТНИЙ')
    expect(rows()).toHaveLength(1)
    for (const [header, value] of [['Area', 'Landing'], ['Type', 'Accessibility'], ['Severity', 'High'], ['Status', 'Open']]) {
      fireEvent.keyDown(screen.getByRole('button', { name: header }), { key: 'Enter' })
      fireEvent.click(await screen.findByRole('menuitemcheckbox', { name: value }))
    }
    click('Date')
    change('Від', '2026-09-10')
    change('До', '2026-09-10')
    expect(rows()).toHaveLength(1)
    change('Від', '2026-09-11')
    expect(rows()).toHaveLength(0)
    click('Скинути')
    expect(rows()).toHaveLength(1)
    fireEvent.keyDown(screen.getByLabelText('Від'), { key: 'Escape' })
    click('Очистити фільтри')
    expect(rows()).toHaveLength(4)
    expect(screen.queryByRole('button', { name: 'Task' })).toBeNull()
    expect(screen.queryByLabelText('Поиск по ID')).toBeNull()
  })

  it('creates, renames and deletes project dictionary values and blocks deleting used values', async () => {
    openAudit()
    fireEvent.click(rows()[0])
    fireEvent.click(within(panel()).getByRole('combobox', { name: 'Area' }))
    click('Видалити Area Registration')
    expect(screen.getByRole('alert').textContent).toContain('використовується')
    click('Перейменувати Area Registration')
    change('Нова назва', 'Sign up')
    click('Зберегти назву')
    expect(rows().some(row => row.textContent?.includes('Sign up'))).toBe(true)
    change('Додати Area', 'Unused')
    click('Додати Area')
    click('Не вказано')
    fireEvent.click(within(panel()).getByRole('combobox', { name: 'Area' }))
    click('Видалити Area Unused')
    expect(screen.queryByRole('button', { name: 'Unused' })).toBeNull()
    fireEvent.keyDown(screen.getByLabelText('Додати Area'), { key: 'Escape' })
    await projectMenu('QP Notes')
    click('Додати зауваження')
    for (const kind of ['Area', 'Type']) {
      fireEvent.click(within(panel()).getByRole('combobox', { name: kind }))
      expect(screen.queryByRole('button', { name: 'Sign up' })).toBeNull()
      expect(screen.queryByRole('button', { name: 'Bug' })).toBeNull()
      change('Додати ' + kind, 'QP ' + kind)
      click('Додати ' + kind)
      fireEvent.keyDown(screen.getByLabelText('Додати ' + kind), { key: 'Escape' })
    }
    change('Назва', 'QP finding')
    click('Створити зауваження')
    expect(rows()[0].textContent).toContain('QP Area')
    expect(rows()[0].textContent).toContain('QP Type')
    await projectMenu('Voicli')
    fireEvent.keyDown(screen.getByRole('button', { name: 'Type' }), { key: 'Enter' })
    expect(screen.queryByRole('menuitemcheckbox', { name: 'QP Type' })).toBeNull()
    fireEvent.keyDown(screen.getByRole('menu'), { key: 'Escape' })
    await projectMenu('QP Notes')
    fireEvent.click(rows()[0])
    fireEvent.click(within(panel()).getByRole('combobox', { name: 'Type' }))
    click('Перейменувати Type QP Type')
    change('Нова назва', 'Custom type')
    click('Зберегти назву')
    expect(rows()[0].textContent).toContain('Custom type')
    click('Видалити Type Custom type')
    expect(screen.getByRole('alert').textContent).toContain('використовується')
    change('Додати Type', 'Temporary')
    click('Додати Type')
    click('Custom type')
    fireEvent.click(within(panel()).getByRole('combobox', { name: 'Type' }))
    click('Видалити Type Temporary')
    expect(screen.queryByRole('button', { name: 'Temporary' })).toBeNull()
  })
})
