// @vitest-environment jsdom
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { cleanup, fireEvent, screen, within } from '@testing-library/react'
import { renderAuthenticatedApp } from '@/test/renderAuthenticatedApp'
import { setFieldValue } from '@/test/fields'
beforeEach(() => vi.stubGlobal('ResizeObserver', class { observe() {} unobserve() {} disconnect() {} }))
afterEach(() => { cleanup(); vi.unstubAllGlobals() })
const click = (name: string) => fireEvent.click(screen.getByRole('button', { name }))
const change = (name: string, value: string) => setFieldValue(screen.getByLabelText(name), value)
const findings = () => within(screen.getByRole('region', { name: 'Зауваження Audit' }))
async function open() { await renderAuthenticatedApp(); click('Audit / Аудит') }
async function project(name: string) { fireEvent.keyDown(screen.getByRole('button', { name: /^Project:/ }), { key: 'Enter' }); fireEvent.click(await screen.findByRole('menuitemradio', { name })) }
describe('Audit sessions UI', () => {
  it('creates/edits/cancels metadata and scopes findings/checks to the selected audit', async () => {
    await open(); click('+ Add audit'); change('Title / Назва', 'Second session'); change('Objective / Мета', 'Review keyboard navigation'); change('Scope / Обсяг', 'Login'); change('Limitations / Обмеження', 'Desktop only'); change('Audit type', 'accessibility'); click('Save Audit')
    expect(within(screen.getByRole('table', { name: 'Audits' })).getAllByRole('row')).toHaveLength(3)
    click('AUDIT-002'); expect(findings().queryByText(/Демо:/)).toBeNull()
    click('Edit Audit'); change('Title / Назва', 'Discard title'); click('Cancel Audit')
    expect(screen.queryByText('Discard title')).toBeNull()
    click('Edit Audit'); change('Title / Назва', 'Updated session'); click('Save Audit')
    expect(screen.getByRole('heading', { name: 'AUDIT-002 — Updated session' })).toBeTruthy()
    click('+ Add audit check'); change('Criterion / Критерій', 'Focus is visible'); change('Result', 'Fail'); change('Comment', 'Low contrast'); click('Save Check')
    expect(within(screen.getByRole('region', { name: 'Audit checks' })).getByText('Fail')).toBeTruthy()
    click('+ Add audit finding'); change('Назва', 'Session-specific finding'); click('Створити зауваження')
    expect(findings().getByText('AUD-005')).toBeTruthy()
    click('← Audits'); click('AUDIT-001')
    expect(findings().queryByText('Session-specific finding')).toBeNull()
    expect(screen.queryByText('Focus is visible')).toBeNull()
    click('← Audits'); click('AUDIT-002')
    expect(findings().getByText('Session-specific finding')).toBeTruthy()
    expect(screen.getByText('Focus is visible')).toBeTruthy()
    await project('QP Notes')
    expect(screen.queryByText('Updated session')).toBeNull()
    expect(screen.queryByText('Session-specific finding')).toBeNull()
    click('+ Add audit'); change('Title / Назва', 'QP session'); expect(screen.queryByRole('option', { name: 'Accessibility' })).toBeNull(); click('Save Audit')
    expect(screen.getByRole('button', { name: 'AUDIT-001' })).toBeTruthy()
  })
  it('completes the session and locks metadata/checks/findings/shared Evidence, preserving history', async () => {
    await open(); click('AUDIT-001')
    expect(screen.queryByRole('button', { name: 'Complete Audit' })).toBeNull()
    click('+ Add audit check'); change('Criterion / Критерій', 'Keyboard navigation'); click('Save Check')
    click('Edit check Keyboard navigation'); change('Result', 'Pass'); change('Comment', 'Verified'); click('Save Check')
    click('+ Add audit check'); change('Criterion / Критерій', 'Mobile navigation'); click('Save Check')
    click('+ Add audit finding'); change('Назва', 'History finding')
    click('Add link'); change('Link name', 'Audit evidence'); change('Evidence URL', 'https://example.com/audit'); click('Save link'); click('Створити зауваження')
    click('Start Audit'); expect(screen.getByText('In Progress', { selector: 'span' })).toBeTruthy()
    click('Complete Audit'); expect(screen.getByRole('alert').textContent).toContain('Неперевірених критеріїв: 1')
    click('Скасувати завершення'); expect(screen.getByRole('button', { name: 'Edit Audit' })).toBeTruthy()
    click('Complete Audit'); click('Підтвердити завершення Audit')
    expect(screen.getByText('Completed', { selector: 'span' })).toBeTruthy()
    for (const name of ['Start Audit', 'Complete Audit', 'Edit Audit', '+ Add audit check', '+ Add audit finding', 'Edit check Keyboard navigation']) expect(screen.queryByRole('button', { name })).toBeNull()
    fireEvent.click(findings().getByText('History finding'))
    const panel = within(screen.getByRole('complementary'))
    expect(panel.getByText('Audit evidence')).toBeTruthy()
    expect(panel.queryByRole('textbox')).toBeNull()
    expect(panel.queryByRole('button', { name: /Add file|Add link|Remove|Зберегти/ })).toBeNull()
    expect(screen.queryByRole('button', { name: /Дії із зауваженням/ })).toBeNull()
    click('Test Cases / Тест-кейси'); click('Audit / Аудит'); click('AUDIT-001')
    expect(screen.getByText('Completed', { selector: 'span' })).toBeTruthy()
    expect(screen.getByText('Verified')).toBeTruthy()
    fireEvent.click(findings().getByText('History finding'))
    expect(screen.getByRole('link', { name: 'Open link' }).getAttribute('href')).toBe('https://example.com/audit')
  })
})
