// @vitest-environment jsdom
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { cleanup, fireEvent, render, screen, within } from '@testing-library/react'
import { renderAuthenticatedApp } from '@/test/renderAuthenticatedApp'
import { CoveragePage } from './CoveragePage'
import { createProjectAreaData } from '@/data/projectAreaMockData'
import { initialRequirementTestCaseLinks } from '@/data/requirementsMockData'

beforeEach(() => vi.stubGlobal('ResizeObserver', class { observe() {} unobserve() {} disconnect() {} }))
afterEach(() => { cleanup(); vi.unstubAllGlobals() })
const click = (name: string) => fireEvent.click(screen.getByRole('button', { name }))
const navigate = (name: string) => fireEvent.click(within(screen.getByRole('navigation', { name: 'Розділи застосунку' })).getByRole('button', { name }))
const change = (name: string, value: string) => fireEvent.change(screen.getByLabelText(name), { target: { value } })
const check = (name: string) => fireEvent.click(screen.getByRole('checkbox', { name }))
const table = () => screen.getByRole('table', { name: 'Requirement coverage' })
const rows = () => within(table()).getAllByRole('row').slice(1)
const summary = () => screen.getByLabelText('Coverage summary').textContent
const row = (code: string) => within(table()).getByRole('button', { name: `Open ${code}` }).closest('tr')!
async function filter(label: string, value: string) {
  fireEvent.keyDown(within(table()).getByRole('button', { name: label }), { key: 'Enter' })
  fireEvent.click(await screen.findByRole('menuitemcheckbox', { name: value }))
}
async function project(name: string) {
  fireEvent.keyDown(screen.getByRole('button', { name: /^Project:/ }), { key: 'Enter' })
  fireEvent.click(await screen.findByRole('menuitemradio', { name }))
}
const start = async () => { await renderAuthenticatedApp(); navigate('Coverage') }

describe('Coverage and bidirectional link management', () => {
  it('shows design coverage, filters/searches and links an uncovered requirement with staged Save/Cancel', async () => {
    await start()
    expect(rows()).toHaveLength(4)
    expect(summary()).toContain('Covered: 3 · Uncovered: 1 · Coverage: 75%')
    expect(screen.queryByRole('button', { name: 'Clear filters' })).toBeNull()
    await filter('Coverage', 'Uncovered')
    expect(rows()).toHaveLength(1)
    click('Open REQ-NAV-001')
    click('Link Test Cases')
    check('TC-001 Login valid user')
    click('Cancel')
    expect(summary()).toContain('Coverage: 75%')
    click('Link Test Cases')
    check('TC-001 Login valid user')
    change('Search test cases', 'WRONG PASSWORD')
    check('TC-002 Wrong password')
    click('Apply selection')
    expect(rows()).toHaveLength(0) // No longer matches Uncovered.
    expect(summary()).toContain('Coverage: 100%')
    const detail = screen.getByRole('complementary', { name: 'Coverage detail' })
    expect(within(detail).getAllByText('Never Run')).toHaveLength(2)
    click('Unlink TC-001')
    expect(summary()).toContain('Coverage: 100%')
    click('Unlink TC-002')
    expect(summary()).toContain('Coverage: 75%')
    click('Close coverage panel')
    expect(screen.queryByRole('complementary')).toBeNull()
    click('Clear filters')
    for (const search of ['req-auth-001', 'USER CAN LOG IN', 'demo-requirement-1']) {
      change('Search by ID or title', search)
      expect(rows()).toHaveLength(1)
      expect(rows()[0].textContent).toContain('REQ-AUTH-001')
    }
  })

  it('edits links from both definition views using the same state, allowing many-to-many and cancel', async () => {
    await start()
    navigate('Requirements')
    click('Open REQ-NAV-001')
    expect(screen.getByRole('heading', { name: 'Test Coverage' })).toBeTruthy()
    click('Link Test Cases')
    check('TC-004 Navigation link')
    click('Apply selection')
    navigate('Test Cases')
    click('Open TC-004')
    expect(screen.getByRole('region', { name: 'Requirements' }).textContent).toContain('REQ-NAV-001')
    click('Manage Requirements')
    check('REQ-AUTH-001 User can log in')
    click('Cancel')
    expect(within(screen.getByRole('region', { name: 'Requirements' })).getAllByRole('listitem')).toHaveLength(1)
    click('Manage Requirements')
    change('Search requirements', 'REQ-AUTH')
    check('REQ-AUTH-001 User can log in')
    check('REQ-AUTH-002 Invalid credentials are rejected')
    click('Apply selection')
    expect(within(screen.getByRole('region', { name: 'Requirements' })).getAllByRole('listitem')).toHaveLength(3)
    click('Manage Requirements')
    check('REQ-NAV-001 User can navigate between pages')
    click('Apply selection')
    expect(within(screen.getByRole('region', { name: 'Requirements' })).getAllByRole('listitem')).toHaveLength(2)
    navigate('Coverage')
    expect(row('REQ-NAV-001').textContent).toContain('Uncovered')
    expect(row('REQ-AUTH-001').textContent).toContain('3Covered')
    navigate('Requirements')
    click('Open REQ-AUTH-001')
    expect(screen.getByRole('region', { name: 'Linked Test Cases' }).textContent).toContain('TC-004')
    click('Unlink TC-004')
    navigate('Test Cases')
    click('Open TC-004')
    expect(within(screen.getByRole('region', { name: 'Requirements' })).getAllByRole('listitem')).toHaveLength(1)
  })

  it('shows reverse traceability and neutral No requirement state and manages links there', async () => {
    await start()
    fireEvent.click(within(screen.getByRole('group', { name: 'Coverage view' })).getByRole('button', { name: 'Traceability / Простежуваність' }))
    const reverse = screen.getByRole('table', { name: 'Test case traceability' })
    expect(within(reverse).getAllByRole('row')).toHaveLength(5)
    expect(within(reverse).getByText('No requirement')).toBeTruthy()
    expect(within(reverse).queryByText('Uncovered')).toBeNull()
    click('Open TC-004')
    click('Manage Requirements')
    check('REQ-AUTH-001 User can log in')
    check('REQ-NAV-001 User can navigate between pages')
    click('Apply selection')
    expect(screen.getByRole('button', { name: 'Open TC-004' }).closest('tr')!.textContent).toContain('2')
    click('Unlink REQ-NAV-001')
    expect(summary()).toContain('Coverage: 75%')
    change('Search by ID or title', 'navigation')
    expect(within(reverse).getAllByRole('row')).toHaveLength(2)
  })

  it('combines Priority, Area, Status, Coverage and Search in the table headers', async () => {
    await start()
    navigate('Requirements')
    click('Open REQ-AUTH-001')
    click('Edit requirement')
    change('Priority', 'high')
    click('Save requirement')
    navigate('Coverage')
    await filter('Area', 'Auth')
    await filter('Priority', 'High')
    await filter('Status', 'Approved')
    await filter('Coverage', 'Covered')
    change('Search by ID or title', 'login')
    expect(rows()).toHaveLength(0)
    change('Search by ID or title', 'log in')
    expect(rows()).toHaveLength(1)
    expect(rows()[0].textContent).toContain('REQ-AUTH-001')
    click('Clear filters')
    expect(rows()).toHaveLength(4)
  })

  it('isolates the list and both pickers by project, including empty projects', async () => {
    await start()
    await project('QP Notes')
    expect(rows()).toHaveLength(0)
    expect(summary()).toContain('Coverage: 0%')
    navigate('Requirements'); click('+ Add requirement')
    change('Title', 'QP requirement'); click('Save requirement')
    click('Link Test Cases')
    expect(screen.queryByRole('checkbox', { name: 'TC-001 Login valid user' })).toBeNull()
    click('Cancel')
    navigate('Test Cases'); click('+ Add test case')
    change('Title', 'QP test'); click('Save test case')
    click('Manage Requirements')
    expect(screen.queryByRole('checkbox', { name: 'REQ-AUTH-001 User can log in' })).toBeNull()
    check('REQ-001 QP requirement'); click('Apply selection')
    navigate('Coverage')
    expect(rows()).toHaveLength(1)
    expect(summary()).toContain('Coverage: 100%')
    click('Open REQ-001'); click('Link Test Cases')
    expect(screen.getByRole('checkbox', { name: 'TC-001 QP test' }).getAttribute('aria-checked')).toBe('true')
    expect(screen.queryByRole('checkbox', { name: 'TC-001 Login valid user' })).toBeNull()
    click('Cancel')
    await project('Voicli')
    expect(rows()).toHaveLength(4)
    expect(summary()).toContain('Coverage: 75%')
    expect(screen.queryByText('QP requirement')).toBeNull()
  })

  it('renders safely with missing/duplicate relations and foreign entities in incoming state', () => {
    const seed = createProjectAreaData()
    const requirements = seed.requirements.voicli.items
    const cases = seed.testCases.voicli.items
    render(<CoveragePage projectId="voicli" requirements={[...requirements, { ...requirements[0], id: 'foreign-req', projectId: 'other', title: 'Foreign requirement' }]} cases={[...cases, { ...cases[0], id: 'foreign-case', projectId: 'other', title: 'Foreign test' }]} areas={seed.areas} types={seed.testCases.voicli.types} executions={[]} links={[...initialRequirementTestCaseLinks, initialRequirementTestCaseLinks[0], { projectId: 'voicli', requirementId: requirements[0].id, testCaseId: 'missing' }]} onLinksChange={vi.fn()} />)
    expect(summary()).toContain('Coverage: 75%')
    expect(rows()).toHaveLength(4)
    click('Open REQ-AUTH-001'); click('Link Test Cases')
    expect(screen.queryByRole('checkbox', { name: /Foreign/ })).toBeNull()
    expect(screen.queryByText('Foreign requirement')).toBeNull()
  })
})
