// @vitest-environment jsdom
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { cleanup, fireEvent, screen, within } from '@testing-library/react'
import { renderAuthenticatedApp } from '@/test/renderAuthenticatedApp'
import { setFieldValue } from '@/test/fields'
beforeEach(() => vi.stubGlobal('ResizeObserver', class { observe() {} unobserve() {} disconnect() {} }))
afterEach(() => { cleanup(); vi.unstubAllGlobals() })
const click = (name: string) => fireEvent.click(screen.getByRole('button', { name }))
const change = (label: string, value: string) => setFieldValue(screen.getByLabelText(label), value)
const linked = () => within(screen.getByRole('region', { name: 'Linked Defects' }))
function addEvidence() { click('Add link'); change('Link name', 'Source proof'); change('Evidence URL', 'https://example.com/source-proof'); click('Save link') }
async function openSmoke() {
  await renderAuthenticatedApp(); click('Open SMK-001'); click('Run Smoke')
  change('Environment / Середовище', 'env-voicli-staging'); change('Build / Збірка', 'build-voicli-26-rc1')
  change('Browser', 'Chrome'); click('Create Draft'); click('TC-001')
}
function fail() {
  change('Result', 'Fail'); change('Actual Result / Фактичний результат', 'Broken product')
  change('Comment', 'Repeated twice'); click('Save result')
}
describe('Smoke and Audit Defect follow-up UI', () => {
  it('creates a Defect from completed Smoke Fail and returns to unchanged snapshot/results without copying Evidence', async () => {
    await openSmoke()
    expect(screen.queryByRole('button', { name: 'Create Defect' })).toBeNull()
    fail(); addEvidence()
    click('Complete Run'); click('Завершити все одно')
    expect(screen.queryByRole('button', { name: 'Save result' })).toBeNull()
    expect(screen.getByRole('button', { name: 'Create Defect' })).toHaveProperty('disabled', false)
    click('Create Defect')
    expect(screen.getByLabelText('Title')).toHaveProperty('value', 'Login valid user')
    expect(screen.getByLabelText('Actual result / Фактичний результат')).toHaveProperty('value', 'Broken product')
    expect(screen.getByLabelText('Build / Збірка')).toHaveProperty('value', 'build-voicli-26-rc1')
    expect(screen.getByLabelText('Environment / Середовище')).toHaveProperty('value', 'env-voicli-staging')
    change('Title', 'Smoke regression defect'); click('Save Defect')
    expect(linked().getByText(/BUG-004 — Smoke regression defect/)).toBeTruthy()
    expect(screen.getByText('Completed', { selector: 'span' })).toBeTruthy()
    expect(screen.getByText('Broken product')).toBeTruthy()
    click('View Defect')
    expect(screen.queryByText('Source proof')).toBeNull()
    expect(screen.getByText('No attachments.')).toBeTruthy()
    expect(screen.getByRole('region', { name: 'Source' }).textContent).toContain('Smoke Run')
    click('View Execution')
    expect(screen.getByRole('heading', { name: 'Login valid user' })).toBeTruthy()
    expect(screen.getByText('Source proof')).toBeTruthy()
    expect(screen.queryByRole('button', { name: 'Save result' })).toBeNull()
    click('Link Existing Defect'); click('Link BUG-001')
    expect(linked().getAllByRole('button', { name: 'View Defect' })).toHaveLength(2)
  })
  it('links the same existing Defect to multiple Smoke failures and retains links per execution', async () => {
    await openSmoke(); fail()
    click('Link Existing Defect'); change('Search existing defects', 'BUG-001'); click('Link BUG-001')
    expect(linked().getAllByRole('button', { name: 'View Defect' })).toHaveLength(1)
    click('Next'); fail(); click('Link Existing Defect'); click('Link BUG-001')
    expect(linked().getByText(/BUG-001/)).toBeTruthy()
    click('Link Existing Defect'); expect(screen.getByRole('button', { name: 'Link BUG-001' })).toHaveProperty('disabled', true)
    fireEvent.keyDown(screen.getByRole('dialog'), { key: 'Escape' })
    click('Previous'); expect(linked().getByText(/BUG-001/)).toBeTruthy()
  })
  it('creates from a completed Audit Finding through the same Defect panel, without changing finding/evidence', async () => {
    await renderAuthenticatedApp(); click('Audit / Аудит'); click('AUDIT-001')
    click('+ Add audit finding'); change('Назва', 'Focus finding'); change('Що виявлено', 'Focus is invisible'); change('Expected / Очікуваний результат', 'Visible focus'); change('Actual / Фактичний результат', 'Invisible focus')
    addEvidence(); click('Створити зауваження')
    click('Start Audit'); click('Complete Audit'); click('Підтвердити завершення Audit')
    fireEvent.click(screen.getByText('Focus finding'))
    click('Create Defect')
    expect(screen.getByLabelText('Title')).toHaveProperty('value', 'Focus finding')
    expect(screen.getByLabelText('Expected result / Очікуваний результат')).toHaveProperty('value', 'Visible focus')
    expect(screen.getByLabelText('Actual result / Фактичний результат')).toHaveProperty('value', 'Invisible focus')
    change('Title', 'Focus defect'); click('Save Defect')
    expect(linked().getByText(/BUG-004 — Focus defect/)).toBeTruthy()
    expect(screen.getByText('Completed', { selector: 'span' })).toBeTruthy()
    expect(screen.queryByRole('button', { name: 'Зберегти зміни' })).toBeNull()
    expect(screen.getByText('Source proof')).toBeTruthy()
    click('View Defect')
    expect(screen.queryByText('Source proof')).toBeNull()
    expect(screen.getByText('No attachments.')).toBeTruthy()
    click('View Finding')
    expect(screen.getByRole('heading', { name: 'Focus finding' })).toBeTruthy()
    click('Link Existing Defect'); click('Link BUG-001')
    expect(linked().getAllByRole('button', { name: 'View Defect' })).toHaveLength(2)
  })
  it('links existing to multiple Audit Findings and hides foreign project Defects from picker', async () => {
    await renderAuthenticatedApp(); click('Defects / Дефекти')
    fireEvent.keyDown(screen.getByRole('button', { name: /^Project:/ }), { key: 'Enter' }); fireEvent.click(await screen.findByRole('menuitemradio', { name: 'QP Notes' }))
    click('+ Add defect'); change('Title', 'Foreign only'); click('Save Defect')
    fireEvent.keyDown(screen.getByRole('button', { name: /^Project:/ }), { key: 'Enter' }); fireEvent.click(await screen.findByRole('menuitemradio', { name: 'Voicli' }))
    click('Audit / Аудит'); click('AUDIT-001')
    const rows = () => document.querySelectorAll('.audit-compact-row')
    fireEvent.click(rows()[0]); click('Link Existing Defect')
    expect(screen.queryByText(/Foreign only/)).toBeNull()
    click('Link BUG-001')
    fireEvent.click(rows()[1]); click('Link Existing Defect'); click('Link BUG-001')
    expect(linked().getByText(/BUG-001/)).toBeTruthy()
    fireEvent.click(rows()[0]); expect(linked().getByText(/BUG-001/)).toBeTruthy()
    change('Назва', 'Unsaved finding')
    expect(screen.getByRole('button', { name: 'Create Defect' })).toHaveProperty('disabled', true)
    click('Зберегти зміни')
    expect(screen.getByRole('button', { name: 'Create Defect' })).toHaveProperty('disabled', false)
  })
})
