// @vitest-environment jsdom
import { setFieldValue } from '@/test/fields'
import { afterAll, afterEach, describe, expect, it, vi } from 'vitest'
import { cleanup, fireEvent, screen, within } from '@testing-library/react'
import { renderAuthenticatedApp } from '@/test/renderAuthenticatedApp'

afterEach(cleanup)
// Radix checkbox sizing uses ResizeObserver, which jsdom does not implement.
vi.stubGlobal('ResizeObserver', class {
  observe = vi.fn()
  unobserve = vi.fn()
  disconnect = vi.fn()
})
afterAll(() => vi.unstubAllGlobals())
const click = (name: string) => fireEvent.click(screen.getByRole('button', { name }))
const change = (name: string, value: string) => setFieldValue(screen.getByLabelText(name), value)
const panel = () => screen.getByRole('complementary', { name: 'Requirement panel' })
const rows = () => within(screen.getByRole('table')).getAllByRole('row').slice(1)
const row = (code: string) => screen.getByRole('button', { name: 'Open ' + code }).closest('tr')!
const start = async () => { await renderAuthenticatedApp(); click('Requirements') }
const check = (name: string) => fireEvent.click(screen.getByRole('checkbox', { name }))
async function menu(trigger: string, action: string, role: 'menuitem' | 'menuitemcheckbox' = 'menuitem') {
  fireEvent.keyDown(screen.getByRole('button', { name: trigger }), { key: 'Enter' })
  fireEvent.click(await screen.findByRole(role, { name: action }))
}
async function project(name: string) {
  fireEvent.keyDown(screen.getByRole('button', { name: /^Project:/ }), { key: 'Enter' })
  fireEvent.click(await screen.findByRole('menuitemradio', { name }))
}

describe('Requirements and test case relations', () => {
  it('creates with multiple links, edits code, unlinks without deleting tests and deletes a requirement', async () => {
    await start()
    click('+ Add requirement')
    expect((screen.getByLabelText('Code') as HTMLInputElement).value).toBe('REQ-001')
    change('Title', 'Demo requirement')
    change('Description', 'A new description')
    change('Source', 'Demo source')
    change('Notes', 'Demo notes')
    click('Manage linked test cases')
    check('TC-001 Login valid user')
    change('Search test cases', 'WRONG PASSWORD')
    check('TC-002 Wrong password')
    click('Apply selection')
    expect(within(screen.getByRole('list', { name: 'Selected test cases' })).getAllByRole('listitem')).toHaveLength(2)
    click('Save requirement')
    expect(rows()).toHaveLength(5)
    expect(row('REQ-001').textContent).toContain('2 tests')
    expect(within(panel()).getByText('A new description')).toBeTruthy()
    const edit = within(panel()).getByRole('button', { name: 'Edit requirement' })
    expect(edit.closest('form')).toBeNull()
    click('Edit requirement')
    change('Code', 'REQ-CUSTOM')
    change('Title', 'Updated requirement')
    click('Unlink TC-001')
    click('Save requirement')
    expect(rows()).toHaveLength(5)
    expect(row('REQ-CUSTOM').textContent).toContain('1 test')
    click('Edit requirement')
    click('Unlink TC-002')
    click('Save requirement')
    expect(row('REQ-CUSTOM').textContent).toContain('0 tests')
    click('Test Cases')
    expect(rows()).toHaveLength(4)
    click('Requirements')
    await menu('Actions REQ-CUSTOM', 'Edit')
    expect(screen.getByLabelText('Title')).toBeTruthy()
    click('Cancel')
    await menu('Actions REQ-CUSTOM', 'Delete')
    click('Cancel')
    expect(rows()).toHaveLength(5)
    await menu('Actions REQ-CUSTOM', 'Delete')
    click('Delete requirement')
    expect(rows()).toHaveLength(4)
    click('Test Cases')
    expect(rows()).toHaveLength(4)
  })

  it('derives many-to-many reverse links and uses current test case code and title', async () => {
    await start()
    click('Test Cases')
    click('Open TC-002')
    const requirements = screen.getByRole('region', { name: 'Requirements' })
    expect(within(requirements).getAllByRole('listitem')).toHaveLength(2)
    expect(requirements.textContent).toContain('REQ-AUTH-001')
    expect(requirements.textContent).toContain('REQ-AUTH-002')
    click('Edit test case')
    change('ID/code', 'TC-RENAMED')
    change('Title', 'Updated case definition')
    click('Save test case')
    expect(screen.getByRole('region', { name: 'Requirements' }).textContent).toContain('REQ-AUTH-001')
    click('Requirements')
    click('Open REQ-AUTH-001')
    const linked = within(panel()).getByRole('region', { name: 'Linked Test Cases' })
    expect(linked.textContent).toContain('TC-RENAMED')
    expect(linked.textContent).toContain('Updated case definition')
    click('Edit requirement')
    click('Unlink TC-RENAMED')
    click('Save requirement')
    click('Test Cases')
    click('Open TC-RENAMED')
    expect(within(screen.getByRole('region', { name: 'Requirements' })).getAllByRole('listitem')).toHaveLength(1)
    expect(screen.getByRole('region', { name: 'Requirements' }).textContent).toContain('REQ-AUTH-002')
  })

  it('combines Area, Status, Coverage and case-insensitive search; clears no-match filters', async () => {
    await start()
    expect(screen.queryByRole('button', { name: 'Clear filters' })).toBeNull()
    await menu('Area', 'Auth', 'menuitemcheckbox')
    await menu('Status', 'Approved', 'menuitemcheckbox')
    await menu('Coverage', 'Covered', 'menuitemcheckbox')
    expect(rows()).toHaveLength(1)
    for (const text of ['req-auth-001', 'USER CAN LOG IN', 'demo-requirement-1']) {
      change('Search by ID or title', text)
      expect(rows()).toHaveLength(1)
    }
    change('Search by ID or title', '')
    await menu('Coverage', 'Not covered', 'menuitemcheckbox')
    expect(rows()).toHaveLength(0)
    expect(screen.getByText('No matching requirements.')).toBeTruthy()
    click('Clear filters')
    expect(rows()).toHaveLength(4)
    await menu('Coverage', 'Not covered', 'menuitemcheckbox')
    expect(rows()).toHaveLength(1)
    expect(rows()[0].textContent).toContain('REQ-NAV-001')
  })

  it('isolates requirements, link choices and reverse links between projects and initializes new projects empty', async () => {
    await start()
    await project('QP Notes')
    expect(rows()).toHaveLength(0)
    click('+ Add requirement')
    expect(within(panel()).queryByRole('checkbox')).toBeNull()
    click('Cancel')
    click('Test Cases')
    click('+ Add test case')
    change('Title', 'QP unique case')
    click('Save test case')
    click('Requirements')
    click('+ Add requirement')
    change('Code', 'REQ-AUTH-001')
    change('Title', 'QP unique requirement')
    expect(screen.queryByRole('checkbox', { name: 'TC-001 Login valid user' })).toBeNull()
    click('Manage linked test cases')
    check('TC-001 QP unique case')
    click('Apply selection')
    click('Save requirement')
    expect(row('REQ-AUTH-001').textContent).toContain('1 test')
    await project('Voicli')
    expect(rows()).toHaveLength(4)
    expect(screen.queryByText('QP unique requirement')).toBeNull()
    click('Test Cases')
    click('Open TC-001')
    expect(screen.getByRole('region', { name: 'Requirements' }).textContent).not.toContain('QP unique requirement')
    await project('QP Notes')
    click('Open TC-001')
    expect(screen.getByRole('region', { name: 'Requirements' }).textContent).toContain('QP unique requirement')
    await menu('Project: QP Notes', 'Додати проєкт')
    change('Назва проєкту', 'Empty requirement project')
    click('Створити проєкт')
    click('Requirements')
    expect(rows()).toHaveLength(0)
    click('+ Add requirement')
    expect(within(panel()).queryByRole('checkbox')).toBeNull()
  })

  it('cleans links and updates Coverage when a test case is deleted', async () => {
    await start()
    expect(row('REQ-AUTH-001').textContent).toContain('2 tests')
    expect(row('REQ-AUTH-002').textContent).toContain('1 test')
    click('Test Cases')
    await menu('Actions TC-002', 'Delete')
    click('Delete test case')
    click('Requirements')
    expect(row('REQ-AUTH-001').textContent).toContain('1 test')
    expect(row('REQ-AUTH-002').textContent).toContain('0 tests')
    click('Open REQ-AUTH-002')
    expect(within(panel()).getByText('No linked test cases.')).toBeTruthy()
  })

  it('validates code, cancels edits and manages Area without deleting used values', async () => {
    await start()
    click('+ Add requirement')
    click('Save requirement')
    expect(screen.getByRole('alert').textContent).toContain('code and title')
    change('Title', 'New requirement')
    change('Code', 'req-auth-001')
    click('Save requirement')
    expect(screen.getByRole('alert').textContent).toContain('already exists')
    click('Cancel')
    click('Open REQ-AUTH-001')
    click('Edit requirement')
    fireEvent.click(within(panel()).getByRole('combobox', { name: 'Area' }))
    click('Видалити Area Auth')
    expect(screen.getByRole('alert').textContent).toContain('used by a requirement')
    click('Перейменувати Area Auth')
    change('Нова назва', 'Accounts')
    click('Зберегти назву')
    expect(row('REQ-AUTH-001').textContent).toContain('Accounts')
    change('Додати Area', 'Temporary')
    click('Додати Area')
    click('Accounts')
    fireEvent.click(within(panel()).getByRole('combobox', { name: 'Area' }))
    click('Видалити Area Temporary')
    expect(screen.queryByRole('button', { name: 'Temporary' })).toBeNull()
    fireEvent.keyDown(screen.getByLabelText('Додати Area'), { key: 'Escape' })
    change('Title', 'Discard this title')
    click('Cancel')
    expect(within(panel()).getByRole('heading', { name: 'User can log in' })).toBeTruthy()
  })
})
