// @vitest-environment jsdom
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { cleanup, fireEvent, screen, waitFor, within } from '@testing-library/react'
import { renderAuthenticatedApp } from '@/test/renderAuthenticatedApp'
import { setFieldValue } from '@/test/fields'
beforeEach(() => vi.stubGlobal('ResizeObserver', class { observe() {} unobserve() {} disconnect() {} }))
afterEach(() => { cleanup(); vi.unstubAllGlobals() })
const click = (name: string) => fireEvent.click(screen.getByRole('button', { name }))
const change = (name: string, value: string) => setFieldValue(screen.getByLabelText(name), value)
const checkbox = (name: string) => fireEvent.click(screen.getByRole('checkbox', { name }))
const open = async () => { await renderAuthenticatedApp(); click('Open SMK-001') }
const createRun = async () => { click('Run Smoke'); change('Environment / Середовище', 'env-voicli-staging'); change('Build / Збірка', 'build-voicli-26-rc1'); click('Create Draft'); await screen.findByText('Draft') }
const executions = () => within(screen.getByRole('table', { name: 'Smoke executions' }))
const panel = () => screen.getByRole('complementary', { name: 'Execution panel' })
const suiteCases = () => within(screen.getByRole('table', { name: 'Suite test cases' }))
async function project(name: string) { fireEvent.keyDown(screen.getByRole('button', { name: /^Project:/ }), { key: 'Enter' }); fireEvent.click(await screen.findByRole('menuitemradio', { name })); await waitFor(() => expect(screen.queryByText('Завантаження даних проєкту…')).toBeNull()) }

describe('Normalized Smoke suites and runs', () => {
  it('creates suite from central cases, reorders cases/prerequisites and cancels definition changes', async () => {
    await renderAuthenticatedApp()
    expect(within(screen.getByRole('table', { name: 'Smoke suites' })).getAllByRole('row')).toHaveLength(3)
    click('+ Add smoke suite'); change('Name', 'Release smoke'); change('Description', 'Release checks')
    click('Add prerequisite'); change('Prerequisite 1', 'API available')
    click('Add prerequisite'); change('Prerequisite 2', 'Test account'); click('Move prerequisite 2 up')
    click('Select Test Cases'); checkbox('TC-001 Login valid user'); change('Search test cases', 'Wrong password'); checkbox('TC-002 Wrong password'); click('Apply selection')
    click('Move test case 2 up'); click('Save Suite'); await screen.findByRole('table', { name: 'Suite test cases' })
    expect(suiteCases().getAllByRole('row')[1].textContent).toContain('TC-002')
    expect(within(screen.getByRole('region', { name: 'Suite prerequisites' })).getAllByRole('listitem').map(item => item.textContent)).toEqual(['Test account', 'API available'])
    expect(screen.queryByRole('checkbox')).toBeNull()
    expect(screen.getByRole('button', { name: '← Smoke' }).closest('.account-bar')).toBeTruthy()
    click('Edit Suite'); change('Name', 'Discard name'); click('Cancel')
    expect(screen.queryByText('Discard name')).toBeNull()
    click('Test Cases / Тест-кейси'); expect(within(screen.getByRole('table')).getAllByRole('row')).toHaveLength(5)
    click('Smoke / Смоук-тестування'); click('Open SMK-003'); expect(screen.getByRole('heading', { name: 'Release smoke' })).toBeTruthy()
  })
  it('runs prerequisites and tests, supports Previous/Next and freezes completed history', async () => {
    await open(); await createRun()
    expect(screen.getByText('Draft')).toBeTruthy()
    expect(screen.getByRole('button', { name: '← Smoke Suite' }).closest('.account-bar')).toBeTruthy()
    expect(executions().getAllByText('Not Run / Не виконано')).toHaveLength(2)
    change('Prerequisite result 1', 'Pass'); change('Prerequisite comment 1', 'API healthy')
    click('Start Run'); expect(await screen.findByText('In Progress')).toBeTruthy()
    click('TC-001'); change('Result', 'Pass'); click('Save result')
    expect(await within(panel()).findByText('Executed by: 42')).toBeTruthy()
    click('Next'); expect(within(panel()).getByRole('heading', { name: 'Wrong password' })).toBeTruthy()
    change('Result', 'Fail'); change('Actual Result / Фактичний результат', 'Unexpected response'); change('Comment', 'Reproduced'); change('Evidence note', 'Capture later'); click('Save result'); await within(panel()).findByText('Reproduced')
    expect(screen.getByRole('button', { name: 'Create Defect' })).toHaveProperty('disabled', false)
    click('Previous'); expect(within(panel()).getByRole('heading', { name: 'Login valid user' })).toBeTruthy()
    expect(screen.queryByRole('button', { name: 'Create Defect' })).toBeNull()
    expect(screen.getByLabelText('Smoke progress').textContent).toContain('Progress: 2 / 2')
    click('Complete Run'); await waitFor(() => expect(screen.queryByRole('button', { name: 'Complete Run' })).toBeNull())
    expect(within(panel()).queryByRole('textbox')).toBeNull(); expect(screen.queryByRole('combobox')).toBeNull()
    click('Next'); expect(within(panel()).getByText('Unexpected response')).toBeTruthy()
    click('← Smoke Suite'); expect(screen.getByRole('button', { name: 'Run #1' })).toBeTruthy()
    click('Run #1'); click('TC-002'); expect(within(panel()).getByText('Reproduced')).toBeTruthy(); expect(within(panel()).getByText('Capture later')).toBeTruthy()
    expect(screen.getByRole('region', { name: 'Run prerequisites' }).textContent).toContain('API healthy')
  })
  it('warns about Not Run and Not Checked and allows completing an incomplete run', async () => {
    await open(); await createRun(); click('Complete Run')
    expect(screen.getByRole('alert').textContent).toContain('2 Test Cases залишаються Not Run. 1 prerequisites залишаються Not Checked')
    click('Cancel'); expect(screen.queryByRole('alert')).toBeNull()
    click('Complete Run'); click('Завершити все одно')
    await waitFor(() => expect(screen.queryByRole('button', { name: 'Start Run' })).toBeNull())
    expect(screen.queryByRole('button', { name: 'Complete Run' })).toBeNull()
    click('TC-001'); expect(within(panel()).queryByRole('button', { name: 'Save result' })).toBeNull()
  })
  it.each(['tests', 'prerequisites'])('warns when only %s remain outstanding', async remaining => {
    await open(); await createRun()
    if (remaining === 'tests') { change('Prerequisite result 1', 'Pass'); await waitFor(() => expect((screen.getByLabelText('Prerequisite result 1') as HTMLSelectElement).value).toBe('Pass')) }
    else {
      click('TC-001'); change('Result', 'Pass'); click('Save result'); await within(panel()).findByText('Executed by: 42'); click('Next'); change('Result', 'Skipped'); click('Save result'); await within(panel()).findByText('Executed by: 42')
    }
    click('Complete Run')
    expect(screen.getByRole('alert').textContent).toContain(remaining === 'tests' ? '2 Test Cases залишаються Not Run. 0 prerequisites' : '0 Test Cases залишаються Not Run. 1 prerequisites')
  })

  it('keeps old snapshots and composition after editing central cases, suite and prerequisites', async () => {
    await open(); await createRun(); click('← Smoke Suite')
    click('Edit Suite'); change('Name', 'Updated suite'); change('Prerequisite 1', 'Updated prerequisite'); click('Remove test case 2')
    click('Select Test Cases'); checkbox('TC-004 Navigation link'); click('Apply selection'); click('Save Suite'); await screen.findByRole('heading', { name: 'Updated suite' })
    click('Test Cases / Тест-кейси'); click('Open TC-001'); click('Edit test case'); change('Title', 'Updated login definition'); click('Save test case')
    await screen.findByRole('heading', { name: 'Updated login definition' })
    click('Smoke / Смоук-тестування'); click('Open SMK-001'); click('Run #1')
    expect(screen.getByRole('heading', { name: 'Main Smoke' })).toBeTruthy()
    expect(executions().getByText('Login valid user')).toBeTruthy(); expect(executions().getByText('Wrong password')).toBeTruthy()
    expect(screen.queryByText('Updated prerequisite')).toBeNull()
    click('← Smoke Suite'); await createRun()
    expect(screen.getByRole('heading', { name: 'Updated suite' })).toBeTruthy()
    expect(executions().getByText('Updated login definition')).toBeTruthy(); expect(executions().getByText('Navigation link')).toBeTruthy()
    expect(screen.getByText('Updated prerequisite')).toBeTruthy()
    click('Test Cases / Тест-кейси')
    fireEvent.keyDown(screen.getByRole('button', { name: 'Actions TC-001' }), { key: 'Enter' }); fireEvent.click(await screen.findByRole('menuitem', { name: 'Delete' })); click('Delete test case')
    await waitFor(() => expect(screen.queryByRole('dialog')).toBeNull())
    click('Smoke / Смоук-тестування'); click('Open SMK-001'); click('Run #1'); click('TC-001')
    expect(within(panel()).getByRole('heading', { name: 'Login valid user' })).toBeTruthy()
  })
  it('isolates suites, selectors and history by project and preserves central many-to-many membership', async () => {
    await open(); await createRun(); await project('QP Notes')
    expect(screen.queryByRole('complementary')).toBeNull()
    expect(screen.queryByRole('button', { name: 'Open SMK-001' })).toBeNull()
    click('+ Add smoke suite'); change('Name', 'QP suite'); click('Select Test Cases')
    expect(screen.queryByRole('checkbox', { name: 'TC-001 Login valid user' })).toBeNull(); click('Cancel'); click('Save Suite'); await screen.findByRole('heading', { name: 'QP suite' })
    expect((screen.getByRole('button', { name: 'Run Smoke' }) as HTMLButtonElement).disabled).toBe(true)
    expect(screen.queryByRole('button', { name: 'Run #1' })).toBeNull()
    await project('Voicli'); click('Open SMK-002'); expect(suiteCases().getByText('TC-001')).toBeTruthy()
    click('← Smoke'); click('Open SMK-001'); expect(suiteCases().getByText('TC-001')).toBeTruthy(); click('Run #1'); expect(executions().getAllByRole('row')).toHaveLength(3)
  })
  it('confirms deletion, preserves sibling suites and refuses to remove a suite with history', async () => {
    await renderAuthenticatedApp(); click('Delete SMK-002'); click('Cancel')
    expect(screen.getByRole('button', { name: 'Open SMK-002' })).toBeTruthy()
    click('Delete SMK-002'); click('Delete Suite')
    await waitFor(() => expect(screen.queryByRole('button', { name: 'Open SMK-002' })).toBeNull())
    click('Open SMK-001'); await createRun(); click('← Smoke Suite'); click('← Smoke'); click('Delete SMK-001'); click('Delete Suite')
    expect((await screen.findByRole('alert')).textContent).toContain('історію запусків')
    click('Cancel'); click('Test Cases / Тест-кейси'); expect(within(screen.getByRole('table')).getAllByRole('row')).toHaveLength(5)
  })
})
