// @vitest-environment jsdom
import { setFieldValue, fieldValue } from '@/test/fields'
import { afterEach, describe, expect, it } from 'vitest'
import { cleanup, fireEvent, render, screen, within } from '@testing-library/react'
import App from '@/App'

afterEach(cleanup)
const click = (name: string) => fireEvent.click(screen.getByRole('button', { name }))
const change = (name: string, value: string) => setFieldValue(screen.getByLabelText(name), value)
const panel = () => screen.getByRole('complementary', { name: 'Test case panel' })
const caseRows = () => within(screen.getByRole('table')).queryAllByRole('row').slice(1)
const start = () => { render(<App />); click('Test Cases') }
const editField = (name: string, value: string) => setFieldValue(within(panel()).getByLabelText(name), value)
async function menu(trigger: string, action: string, role: 'menuitem' | 'menuitemcheckbox' | 'menuitemradio' = 'menuitem') {
  fireEvent.keyDown(screen.getByRole('button', { name: trigger }), { key: 'Enter' })
  fireEvent.click(await screen.findByRole(role, { name: action }))
}
async function project(name: string) {
  fireEvent.keyDown(screen.getByRole('button', { name: /^Project:/ }), { key: 'Enter' })
  fireEvent.click(await screen.findByRole('menuitemradio', { name }))
}
function addStep(action: string, expected: string) {
  click('+ Add step')
  const actions = within(panel()).getAllByLabelText('Action')
  const results = within(panel()).getAllByLabelText('Expected / Очікуваний результат')
  setFieldValue(actions.at(-1)!, action)
  setFieldValue(results.at(-1)!, expected)
}
function conditionSection(name: string) {
  return within(screen.getByRole('heading', { name, level: 3 }).parentElement!)
}

describe('Project Test Cases', () => {
  it('keeps Edit outside the form so entering edit mode cannot submit it', () => {
    start()
    click('Open TC-001')
    const edit = within(panel()).getByRole('button', { name: 'Edit test case' })
    expect(edit.closest('form')).toBeNull()
    expect(edit.getAttribute('type')).toBe('button')
    fireEvent.click(edit)
    expect(edit.isConnected).toBe(false)
    editField('Title', 'Changed from panel header')
    expect(within(panel()).getByRole('button', { name: 'Save test case' }).getAttribute('type')).toBe('submit')
    expect(caseRows()[0].textContent).toContain('Login valid user')
    click('Save test case')
    expect(caseRows()[0].textContent).toContain('Changed from panel header')
  })

  it('opens edit mode from row actions and saves the changed title', async () => {
    start()
    await menu('Actions TC-001', 'Edit')
    expect(within(panel()).getByLabelText('Title')).toBeTruthy()
    editField('Title', 'Updated through row menu')
    click('Save test case')
    click('Close test case panel')
    click('Open TC-001')
    expect(within(panel()).getByRole('heading', { name: 'Updated through row menu' })).toBeTruthy()
  })
  it('creates with auto code, orders structured steps and conditions, then edits and deletes', async () => {
    start()
    click('+ Add test case')
    expect((screen.getByLabelText('ID/code') as HTMLInputElement).value).toBe('TC-005')
    editField('Title', 'New scenario')
    addStep('First action', 'First expectation')
    addStep('Second action', 'Second expectation')
    click('Move step 2 up')
    expect(fieldValue(within(panel()).getAllByLabelText('Action')[0])).toBe('Second action')
    expect(fieldValue(within(panel()).getAllByLabelText('Expected / Очікуваний результат')[0])).toBe('Second expectation')
    for (const label of ['Preconditions / Передумови', 'Postconditions']) {
      fireEvent.click(conditionSection(label).getByRole('button', { name: 'Add item' }))
      editField(label + ' 1', 'First condition')
      fireEvent.click(conditionSection(label).getByRole('button', { name: 'Add item' }))
      editField(label + ' 2', 'Second condition')
      click('Move ' + label + ' item 2 up')
    }
    click('Save test case')
    expect(caseRows()).toHaveLength(5)
    const steps = within(panel()).getByRole('region', { name: 'Steps' })
    expect(within(steps).getAllByRole('paragraph').map(p => p.textContent)).toEqual(['Second action', 'Second expectation', 'First action', 'First expectation'])
    expect(conditionSection('Preconditions / Передумови').getAllByRole('listitem')[0].textContent).toBe('Second condition')
    click('Edit test case')
    editField('ID/code', 'TC-CUSTOM-001')
    editField('Title', 'Edited scenario')
    click('Move step 1 down')
    click('Delete step 2')
    click('Delete Postconditions item 1')
    click('Save test case')
    expect(caseRows()).toHaveLength(5)
    expect(screen.getByRole('button', { name: 'Open TC-CUSTOM-001' })).toBeTruthy()
    expect(within(panel()).queryByText('Second action')).toBeNull()
    click('Close test case panel')
    expect(screen.queryByRole('complementary')).toBeNull()
    expect(document.querySelector('.tc-with-panel')).toBeNull()
    click('Open TC-CUSTOM-001')
    expect(within(panel()).getByText('First expectation')).toBeTruthy()
    await menu('Actions TC-CUSTOM-001', 'Delete')
    click('Cancel')
    expect(caseRows()).toHaveLength(5)
    await menu('Actions TC-CUSTOM-001', 'Delete')
    click('Delete test case')
    expect(caseRows()).toHaveLength(4)
    expect(screen.queryByRole('complementary')).toBeNull()
  })

  it('combines Area, Priority, Type and Status with case-insensitive code, id and title search', async () => {
    start()
    await menu('Area', 'Auth', 'menuitemcheckbox')
    await menu('Priority', 'High', 'menuitemcheckbox')
    await menu('Type', 'Functional', 'menuitemcheckbox')
    await menu('Status', 'Active', 'menuitemcheckbox')
    expect(caseRows()).toHaveLength(1)
    for (const search of ['tc-001', 'VALID USER', 'demo-test-case-1']) {
      change('Search by ID or title', search)
      expect(caseRows()).toHaveLength(1)
    }
    change('Search by ID or title', 'absent')
    expect(caseRows()).toHaveLength(0)
    await menu('Type', 'Negative', 'menuitemcheckbox')
    change('Search by ID or title', '')
    expect(caseRows()).toHaveLength(1)
    expect(caseRows()[0].textContent).toContain('Wrong password')
    click('Clear filters')
    expect(caseRows()).toHaveLength(4)
    expect(screen.queryByRole('button', { name: 'Clear filters' })).toBeNull()
    click('ID')
    expect(caseRows()[0].textContent).toContain('TC-004')
  })

  it('isolates projects, allows matching codes across projects and retains changes on navigation', async () => {
    start()
    await project('QP Notes')
    expect(caseRows()).toHaveLength(0)
    click('+ Add test case')
    expect((screen.getByLabelText('ID/code') as HTMLInputElement).value).toBe('TC-001')
    editField('Title', 'QP scenario')
    click('Save test case')
    await project('Voicli')
    expect(caseRows()).toHaveLength(4)
    expect(screen.queryByText('QP scenario')).toBeNull()
    await project('QP Notes')
    expect(caseRows()).toHaveLength(1)
    click('Audit')
    click('Test Cases')
    expect(caseRows()[0].textContent).toContain('QP scenario')
    await menu('Project: QP Notes', 'Додати проєкт')
    change('Назва проєкту', 'New case project')
    click('Створити проєкт')
    click('Test Cases')
    expect(caseRows()).toHaveLength(0)
  })

  it('validates required values and duplicate code; cancel preserves the saved definition', () => {
    start()
    click('+ Add test case')
    click('Save test case')
    expect(screen.getByRole('alert').textContent).toContain('code and title')
    editField('Title', 'Duplicate')
    editField('ID/code', 'tc-001')
    click('Save test case')
    expect(screen.getByRole('alert').textContent).toContain('already exists')
    editField('ID/code', 'TC-005')
    addStep('', '')
    click('Save test case')
    expect(screen.getByRole('alert').textContent).toContain('Action and Expected')
    click('Cancel')
    expect(caseRows()).toHaveLength(4)
    click('Open TC-001')
    click('Edit test case')
    editField('Title', 'Discard me')
    click('Cancel')
    expect(within(panel()).getByRole('heading', { name: 'Login valid user' })).toBeTruthy()
  })

  it('manages independent project dictionaries, renames references and prevents deletion while used', async () => {
    start()
    click('Open TC-001')
    click('Edit test case')
    fireEvent.click(within(panel()).getByRole('combobox', { name: 'Area' }))
    click('Видалити Area Auth')
    expect(screen.getByRole('alert').textContent).toContain('used by a test case')
    click('Перейменувати Area Auth')
    change('Нова назва', 'Accounts')
    click('Зберегти назву')
    expect(caseRows()[0].textContent).toContain('Accounts')
    change('Додати Area', 'Temporary')
    click('Додати Area')
    click('Accounts')
    fireEvent.click(within(panel()).getByRole('combobox', { name: 'Area' }))
    click('Видалити Area Temporary')
    expect(screen.queryByRole('button', { name: 'Temporary' })).toBeNull()
    fireEvent.keyDown(screen.getByLabelText('Додати Area'), { key: 'Escape' })
    fireEvent.click(within(panel()).getByRole('combobox', { name: 'Type' }))
    change('Додати Type', 'Custom type')
    click('Додати Type')
    fireEvent.keyDown(screen.getByLabelText('Додати Type'), { key: 'Escape' })
    click('Save test case')
    expect(caseRows()[0].textContent).toContain('Custom type')
    await project('QP Notes')
    click('+ Add test case')
    fireEvent.click(within(panel()).getByRole('combobox', { name: 'Type' }))
    expect(screen.queryByRole('button', { name: 'Custom type' })).toBeNull()
    expect(screen.queryByRole('button', { name: 'Functional' })).toBeNull()
  })
})
