import { useContext, useState } from 'react'
import { DictionaryContext, type DictionaryKind } from './dictionaryContext'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover'

export function AuditDictionarySelect({ kind, value, onChange, id, manage = false }: { kind: DictionaryKind; value: string; onChange: (value: string) => void; id: string; manage?: boolean }) {
  const dictionary = useContext(DictionaryContext)
  const [open, setOpen] = useState(false), [editing, setEditing] = useState<string>(), [name, setName] = useState(''), [error, setError] = useState(''), [pending, setPending] = useState(false)
  const label = kind === 'area' ? 'Area' : 'Type', values = dictionary[kind]
  if (!manage) return <div className="field"><label htmlFor={id}>{label}</label><select id={id} className="audit-select" value={value} onChange={event => onChange(event.target.value)}><option value="">Не вказано</option>{values.map(option => <option key={option.id} value={option.id}>{option.name}</option>)}</select></div>
  return <div className="field"><label htmlFor={id}>{label}</label><Popover open={open} onOpenChange={next => { setOpen(next); setError(''); setEditing(undefined); setName('') }}><PopoverTrigger asChild><Button id={id} variant="outline" role="combobox" aria-expanded={open} className="audit-dictionary-trigger">{values.find(option => option.id === value)?.name || 'Виберіть…'}</Button></PopoverTrigger><PopoverContent className="audit-dictionary-popover">
    <Button variant="ghost" size="sm" onClick={() => { onChange(''); setOpen(false) }}>Не вказано</Button><div className="audit-dictionary-values">{values.map(option => <div key={option.id} className="audit-dictionary-row"><Button variant="ghost" size="sm" onClick={() => { onChange(option.id); setOpen(false) }}>{option.name}</Button><Button variant="ghost" size="sm" aria-label={`Перейменувати ${label} ${option.name}`} onClick={() => { setEditing(option.id); setName(option.name); setError('') }}>✎</Button><Button variant="ghost" size="sm" disabled={pending} aria-label={`Видалити ${label} ${option.name}`} onClick={async () => { setPending(true); try { const message = await dictionary.remove(kind, option.id); setError(message) } catch (cause) { setError(cause instanceof Error ? cause.message : 'Не вдалося видалити значення.') } finally { setPending(false) } }}>×</Button></div>)}</div>
    <label htmlFor={`${id}-name`}>{editing ? 'Нова назва' : `Додати ${label}`}</label><Input id={`${id}-name`} value={name} onChange={event => setName(event.target.value)} /><Button size="sm" disabled={pending} onClick={async () => { const normalized = name.trim(); if (!normalized) { setError('Введіть назву.'); return } if (values.some(option => option.id !== editing && option.name.toLowerCase() === normalized.toLowerCase())) { setError('Таке значення вже існує.'); return } setPending(true); try { const savedId = await dictionary.save(kind, normalized, editing); if (!editing) onChange(savedId); setEditing(undefined); setName(''); setError('') } catch (cause) { setError(cause instanceof Error ? cause.message : 'Не вдалося зберегти значення.') } finally { setPending(false) } }}>{editing ? 'Зберегти назву' : `Додати ${label}`}</Button>{error && <p role="alert" className="form-error">{error}</p>}
  </PopoverContent></Popover></div>
}
